# Feuille de TP3 - Partie A : Manipulation de fonctions


In [1]:
# Import des modules
import numpy as np

**Attention :**
+ On rappelle que les noms de fonctions **ne doivent pas commencer par &laquo;_&raquo; ni contenir de caractères accentués**.
+ Les tableaux sont typées. Lorsque vous modifier un élément d'une matrice, si les types sont différents, une conversion a lieu qui peut parfois engendrer des bugs... Voici un exemple pour illustrer cela.

In [40]:
A = np.array([[1,2], [3,4]])
print(A)
A[0,0] = 1.5 # 1.5 va être converti en entier !
print(A)
print(type(A), type(A[0,0]))
A = np.array([[1.,2], [3,4]])
print(A)
A[0,0] = 1.5 # Pas de conversion
print(A)
print(type(A), type(A[0,0]))
A = np.array([[1,2], [3,4]], dtype='float128')
print(A)
A[0,0] = 1.5
print(A)
print(type(A), type(A[0,0]))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'> <class 'numpy.int64'>
[[1. 2.]
 [3. 4.]]
[[1.5 2. ]
 [3.  4. ]]
<class 'numpy.ndarray'> <class 'numpy.float64'>
[[1. 2.]
 [3. 4.]]
[[1.5 2. ]
 [3.  4. ]]
<class 'numpy.ndarray'> <class 'numpy.float128'>


## Exercice 1 : Cryptographie basique : code de César (ou *Caesar cypher*)

Le principe de ce code est de "décaler" les lettres. Par exemple, si la clef choisie est 1, la lettre A sera remplacée par B, la lettre B par C, etc. Nous nous proposons ici de fabriquer une fonction de cryptage et de décryptage pour la clef 13.

#### a. <font color=red>Importer</font> le module `codecs` et tester les commandes `print(codecs.encode("abc", "rot+13"))` et `print(codecs.encode("abc", "rot-13"))` 

In [4]:
import codecs
print(codecs.encode("abc", "rot+13"))
print(codecs.encode("abc", "rot-13"))

nop
abc


Comparer avec les 14, 15 et $16^\text{ème}$ lettres de l'alphabet. 
#### b. Proposer une fonction `crypter()` qui demande à l'utilisateur de saisir une chaîne de caractères et affiche sa version codée.

In [8]:
# Mettre votre fonction ici
def crypter():
    """ Demande de saisir un message puis affiche sa version cryptée. """
    mes = input("Donner une phrase à coder: ")
    print(codecs.encode(mes, "rot+13"))

#### c. Ecrire une fonction `decrypter()`qui demande à l'utilisateur de saisir une chaîne de caractères encodée et affiche sa version décodée.

In [11]:
def decrypt(mes):
    print(codecs.encode(mes, "rot-13"))

#### d.Tester la fonction \verb+crypter()+ avec un message déjà crypté. Expliquer le résultat (indice : il y a 26 lettres dans l'alphabet).


In [16]:
crypter()


abc


## Exercice 2
### Question 1
A l'aide du module `numpy`, implémenter informatiquement la fonction $f : x \mapsto \sin(\pi x)$.

In [13]:
def sin(x):
    return np.sin(np.pi * x)


### Question 2
Ecrire une fonction qui convertit une vitesse depuis des $km/h$ vers des miles par heure puis des noeuds. On rappelle que 1 mile = 1609 m et 1 noeud $= 0.514 m.s^{-1}$. 

In [28]:
def miles_knots(kmh):
    mph = float((kmh * 1000) * 1 / 1609)
    knots = float((kmh / 3.6) * (1 / 0.514))
    return mph, knots

In [29]:
print(miles_knots(30))

(18.645121193287757, 16.212710765239947)


### Question 3

   1. Ecrire une fonction qui prend en argument un tableau et renvoie un tableau de même taille rempli par le nombre décimal $3.0$ .
   2. A l'aide de la fonction numpy`isscalar` écrire une fonction qui prend un argument \verb+x+ et renvoie 3.0 si `x` est un scalaire et un tableau de 3.0 s'il s'agit d'un tableau.

In [30]:
def conv_tab(x):
    return np.ones(shape=x.shape) * 3.0

def test_scalar(x):
    if np.isscalar(x):
        return 3.0
    else:
        return conv_tab(x)

### Question 4
L'aire d'un triangle peut être calculée à partir des coordonnées de ses trois sommets par la formule :
\begin{equation*}
 	\mathcal{A} = \frac{1}{2}\big\vert (x_1 - x_3)(y_2-y_1)  - (x_1-x_2)(y_3 - y_1) \big \vert
\end{equation*}
Ecrire une fonction qui prend comme argument un tableau bi-dimensionnel dont chaque ligne est la coordonnée $(x,y)$ d'un sommet et renvoie son aire.

In [31]:
def aire(sommets):
    return (1/2) * np.abs((sommets[0,0] - sommets[2,0]) * (sommets[1,1] - sommets[0,1]) - (sommets[0,0] - sommets[1,0])*(sommets[2,1] - sommets[0,1]))

### Question 5
Ecrire une fonction qui prend en argument un tableau et remplace ces coefficients strictement positif par $1$ et ses coefficients strictement négatifs par $-1$.

In [32]:
def sign(x):
    tab = [-1 if elt < 0 else (1 if elt > 0 else 0) for elt in x]
    return tab

## Exercice : comparaison de nombre flottants

1. Importez le module \verb!scipy.linalg! comme \verb!slin!, définissez une matrice $A$ (si possible inversible) et un vecteur $u$. Calculez le déterminant de A, inversez la matrice, calculez $x=A^{-1}u$, puis calculez la norme de $Ax-u$. Comparer $Ax$ et $u$.
2. Testez également la commande \verb!allclose! pour comparer $Ax$ et $u$.
3. Recommencez en résolvant le système linéaire par la commande \verb!solve!.

In [37]:
import scipy.linalg as slin

A = np.array([[3,2,2], [5,6,7], [8,9,10]])
u = np.array([1,2,3])

print(A)
print(u)

Ainv = slin.inv(A)

print(Ainv)

x = np.dot(slin.inv(A), u)

print(x)

print(slin.norm(np.dot(A, x) - u))
print(np.dot(A,x) > u)

[[ 3  2  2]
 [ 5  6  7]
 [ 8  9 10]]
[1 2 3]
[[ 1.          0.66666667 -0.66666667]
 [-2.         -4.66666667  3.66666667]
 [ 1.          3.66666667 -2.66666667]]
[ 0.33333333 -0.33333333  0.33333333]
2.2644195468014703e-15
[ True  True  True]


In [38]:
print(np.allclose(np.dot(A,x), u))

True


In [39]:
print(slin.solve(A, u))

[ 0.33333333 -0.33333333  0.33333333]
