# Feuille de TP3 - Partie A : Manipulation de fonctions


In [1]:
# Import des modules
import numpy as np

**Attention :**
+ On rappelle que les noms de fonctions **ne doivent pas commencer par &laquo;_&raquo; ni contenir de caractères accentués** (plus précisément, les fonctions qui commencent par &laquo;_&raquo; ne peuvent pas être importées dans un autre module).
+ Les tableaux sont typées. Lorsque vous modifiez un élément d'une matrice, si les types sont différents, une conversion a lieu qui peut parfois engendrer des bugs... Voici un exemple pour illustrer cela.

In [ ]:
A = np.array([[1,2], [3,4]])
print(A)
A[0,0] = 1.5 # 1.5 va être converti en entier !
print(A)
print(type(A), type(A[0,0]))
A = np.array([[1.,2], [3,4]])

print(A)
A[0,0] = 1.5 # Pas de conversion
print(A)
print(type(A), type(A[0,0]))
A = np.array([[1,2], [3,4]], dtype=float)
print(A)
A[0,0] = 1.5
print(A)
print(type(A), type(A[0,0]))

## Exercice 1 : Cryptographie basique : code de César (ou *Caesar cypher*)

Le principe de ce code est de "décaler" les lettres. Par exemple, si la clef choisie est 1, la lettre A sera remplacée par B, la lettre B par C, etc. Nous nous proposons ici de fabriquer une fonction de cryptage et de décryptage pour la clef 13.

#### a. <font color=red>Importer</font> le module `codecs` et tester les commandes `print(codecs.encode("abc", "rot+13"))` et `print(codecs.encode("abc", "rot-13"))` 

In [2]:
import codecs
print(codecs.encode("abc", "rot+13"))
print(codecs.encode("abc", "rot-13"))

nop
nop


Comparer avec les 14, 15 et 16<sup>ème</sup> lettres de l'alphabet. 
#### b. Proposer une fonction `crypter()` qui demande à l'utilisateur de saisir une chaîne de caractères et affiche sa version codée.

In [3]:
# Mettre votre fonction ici
def crypter():
    """ Demande de saisir un message puis affiche sa version cryptée. """
    mes = input("Donner une phrase à coder: ")
    print(codecs.encode(mes, "rot+13"))

#### c. Ecrire une fonction `decrypter()` qui demande à l'utilisateur de saisir une chaîne de caractères encodée et affiche sa version décodée.

In [4]:
def decrypt(mes):
    print(codecs.encode(mes, "rot-13"))

#### d.Tester la fonction `crypter()` avec un message déjà crypté. Expliquer le résultat (indice : il y a 26 lettres dans l'alphabet).


In [5]:
crypter()

abc


## Exercice 2
### Question 1
A l'aide du module `numpy`, implémenter informatiquement la fonction $f : x \mapsto \sin(\pi x)$.

In [6]:
def sin(x):
    return np.sin(np.pi * x)

### Question 2
Ecrire une fonction qui convertit une vitesse depuis des $km/h$ vers des miles par heure puis des noeuds. On rappelle que 1 mile = 1609 m et 1 noeud $= 0.514 m.s^{-1}$. 

In [7]:
def miles_knots(kmh):
    mph = float((kmh * 1000) * 1 / 1609)
    knots = float((kmh / 3.6) * (1 / 0.514))
    return mph, knots

### Question 3

   1. Ecrire une fonction qui prend en argument un tableau et renvoie un tableau de même taille rempli par le nombre à virgule flottante $3.0$ .
   2. A l'aide de la fonction numpy `isscalar` écrire une fonction qui prend un argument `x` et renvoie $3.0$ si `x` est un scalaire et un tableau de $3.0$ s'il s'agit d'un tableau.

In [11]:
def conv_tab(x):
    return np.ones(shape=x.shape) * 3.0

def test_scalar(x):
    if np.isscalar(x):
        return 3.0
    else:
        return conv_tab(x)

### Question 4
L'aire d'un triangle peut être calculée à partir des coordonnées de ses trois sommets par la formule :
\begin{equation*}
 	\mathcal{A} = \frac{1}{2}\big\vert (x_1 - x_3)(y_2-y_1)  - (x_1-x_2)(y_3 - y_1) \big \vert
\end{equation*}
Ecrire une fonction qui prend comme argument un tableau bi-dimensionnel dont chaque ligne est la coordonnée $(x,y)$ d'un sommet et renvoie son aire.

In [12]:
def aire(sommets):
    return (1/2) * np.abs((sommets[0,0] - sommets[2,0]) * (sommets[1,1] - sommets[0,1]) - (sommets[0,0] - sommets[1,0])*(sommets[2,1] - sommets[0,1]))

### Question 5
Ecrire une fonction qui prend en argument un tableau et remplace ces coefficients strictement positif par $1$ et ses coefficients strictement négatifs par $-1$.

In [13]:
def sign(x):
    tab = [-1 if elt < 0 else (1 if elt > 0 else 0) for elt in x]
    return tab

## Exercice : comparaison de nombre flottants

Le module `scipy.linalg' contient des fonctions classiques d'algère linéaire. En particulier, il fournit les fonctions :
   * `inv` qui prend en argument une tableau de dimension 2  correspondant à une matrice carrée et qui renvoie son inverse (s'il existe),
   * `norm` qui prend un vecteur est renvoie sa norme 2 (par défaut) et qui fonctionne aussi pour des matrices (voir l'aide pour connaître les normes possibles),
   * solve qui prend en argument un tableau de dimension 2 représentant une matrice $A$ et un tableau de dimension 1 représentant un vecteur $v$ et cherche à résoudre Ax=b.

1. Importez le module `scipy.linalg` comme `slin`, définissez une matrice $A$ (si possible inversible) et un vecteur $u$. Calculez le déterminant de $A$, inversez la matrice, calculez $x=A^{-1}u$, puis calculez la norme de $Ax-u$. Comparer $Ax$ et $u$.
2. Testez également la commande `allclose` pour comparer $Ax$ et $u$.
3. Recommencez en résolvant le système linéaire par la commande `solve`.

In [14]:
import scipy.linalg as slin

A = np.array([[3,2,2], [5,6,7], [8,9,10]])
u = np.array([1,2,3])

print(A)
print(u)

Ainv = slin.inv(A)

print(Ainv)

x = np.dot(slin.inv(A), u)

print(x)

print(slin.norm(np.dot(A, x) - u))
print(np.dot(A,x) > u)

[[ 3  2  2]
 [ 5  6  7]
 [ 8  9 10]]
[1 2 3]
[[ 1.          0.66666667 -0.66666667]
 [-2.         -4.66666667  3.66666667]
 [ 1.          3.66666667 -2.66666667]]
[ 0.33333333 -0.33333333  0.33333333]
2.2644195468014703e-15
[ True  True  True]


In [15]:
print(np.allclose(np.dot(A,x), u))

True


In [16]:
print(slin.solve(A, u))

[ 0.33333333 -0.33333333  0.33333333]


# Exerice : itérer une fonction

1 . Ecrire une fonction `itere` :

* qui prend en argument une fonction `f` (représentant une fonction mathématiques $f : x \in \mathbb{R} \mapsto f(x)$, un réel $x$ et un entier $n$,
* qui renvoie l'itérée n-ième de $f$ en x (*ie* $f^n (x) = f\circ\big(f^{n-1}(x)\big) = f\circ f \circ f \dots f(x)$)

2. Tester la fonction itere pour $f_a x \mapsto 0.5*(\frac{x}{a} - x)$ et $a=11$ puis $a=3$ et différentes valeurs de $n$.

In [17]:
def itere(f,x,n):
    if(type(n)!=int or n<0):
        raise ValueError("n n'est pas un entier positif !")
    if n==1 :
        return f(x)
    else :
        return f(itere(f,x,n-1))
    
for a in [11,3]:
    for n in range(1,10):
        print("approximation de la racine de ",a, "après",n,"itérées :", itere(lambda x:0.5*(a/x+x),1.,n))

approximation de la racine de  11 après 1 itérées : 6.0
approximation de la racine de  11 après 2 itérées : 3.9166666666666665
approximation de la racine de  11 après 3 itérées : 3.3625886524822697
approximation de la racine de  11 après 4 itérées : 3.316938934730457
approximation de la racine de  11 après 5 itérées : 3.3166248052315686
approximation de la racine de  11 après 6 itérées : 3.3166247903554
approximation de la racine de  11 après 7 itérées : 3.3166247903554
approximation de la racine de  11 après 8 itérées : 3.3166247903554
approximation de la racine de  11 après 9 itérées : 3.3166247903554
approximation de la racine de  3 après 1 itérées : 2.0
approximation de la racine de  3 après 2 itérées : 1.75
approximation de la racine de  3 après 3 itérées : 1.7321428571428572
approximation de la racine de  3 après 4 itérées : 1.7320508100147274
approximation de la racine de  3 après 5 itérées : 1.7320508075688772
approximation de la racine de  3 après 6 itérées : 1.732050807568877

3. Remarque que pour $a>0$, $f_a(x)=x$ si et seulement si $x = \sqrt(a)$. Ecrire alors un fonction `itere_seuil` qui :
    * qui prend en argument une fonction `f` (représentant une fonction mathématiques $f : x \in \mathbb{R} \mapsto f(x)$, un seuil `epsilon` et un réel `x`,
    * l'argument $x$ pourra être pris égal à 1 par défaut,
    * qui renvoie l'itérée n-ième de $f$ en x (*ie* $f^n(x)$) où $n$ est le plus petit entier tel que $\vert(f^{n+1}(x)-f^n(x)\vert \leqslant \varepsilon$.
    
Tester pour la même fonction $f$ que précédement et $\varepsilon = 1e-6$ et $a = 3$ et 11.

In [18]:
def itere_seuil(f,epsilon,x=1.):
    if(epsilon <=0):
        raise ValueError("epsilon n'est pas strictement positif!")
    diff = max(1, 2*epsilon)
    res = x
    while(diff>epsilon):
        res,x  = f(res), res
        diff = np.abs(res-x)
    return res
    
for a in [11,3]:
    print("approximation de la racine de ",a," :", itere_seuil(lambda x:0.5*(a/x+x),0.01))
    print("la valeur à trouver est ",np.sqrt(a))

approximation de la racine de  11  : 3.3166248052315686
la valeur à trouver est  3.3166247903554
approximation de la racine de  3  : 1.7320508100147274
la valeur à trouver est  1.7320508075688772


4. Afin d'éviter une boucle infinie, ajouter un nombre maximum d'itération. Ce nombre pourra être de $10^6$ par défaut. La fonction devra de plus renvoyer le nombre d'itération faites.
 Tester votre condition d'arrêt pour $x \mapsto 2 x$.

In [19]:
def itere_seuil(f,epsilon,x=1.,ite_max=1e4):
    if(epsilon <=0):
        raise ValueError("epsilon n'est pas strictement positif!")
    diff = max(1, 2*epsilon)
    res = x
    ite=0
    while(diff>epsilon and ite<ite_max):
        res,x  = f(res), res
        diff = np.abs(res-x)
        ite +=1
    return res, ite
    
for a in [11,3,0.8]:
    res, ite = itere_seuil(lambda x:0.5*(a/x+x),1e-6)
    print("approximation de la racine de ",a," :", res, 'trouvée en ',ite,"itérations.")
    print("la valeur à trouver est ",np.sqrt(a))
    
print("pour une mauvaise fonction il y a un test d'arrêt :", itere_seuil(lambda x:2*x,0.01))  

approximation de la racine de  11  : 3.3166247903554 trouvée en  6 itérations.
la valeur à trouver est  3.3166247903554
approximation de la racine de  3  : 1.7320508075688772 trouvée en  5 itérations.
la valeur à trouver est  1.7320508075688772
approximation de la racine de  0.8  : 0.894427190999916 trouvée en  4 itérations.
la valeur à trouver est  0.8944271909999159
pour une mauvaise fonction il y a un test d'arrêt : (inf, 1025)
